/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AddRemoveButtonComponent: (typeof import("./src/components/ui/AddRemoveComponent/AddRemoveButtonComponent.vue"))["default"];
    AddRemoveComponent: (typeof import("./src/components/ui/AddRemoveComponent/AddRemoveComponent.vue"))["default"];
    BasketCardComponent: (typeof import("./src/components/Basket/BasketCardComponent.vue"))["default"];
    BasketCardsComponent: (typeof import("./src/components/Basket/BasketCardsComponent.vue"))["default"];
    BasketSummaryComponent: (typeof import("./src/components/Basket/BasketSummaryComponent.vue"))["default"];
    BreadcrumbsComponent: (typeof import("./src/components/ui/BreadcrumbsComponent/BreadcrumbsComponent.vue"))["default"];
    ButtonComponent: (typeof import("./src/components/ui/ButtonComponent/ButtonComponent.vue"))["default"];
    Card: (typeof import("./src/components/Product/Card/Card.vue"))["default"];
    CardComponent: (typeof import("./src/components/ui/CardComponent/CardComponent.vue"))["default"];
    CardsComponent: (typeof import("./src/components/ui/CardsComponent/CardsComponent.vue"))["default"];
    CategoriesBreadcrumbsComponent: (typeof import("./src/components/Categories/CategoriesBreadcrumbsComponent.vue"))["default"];
    CategoriesContentComponent: (typeof import("./src/components/Categories/CategoriesContentComponent.vue"))["default"];
    CategoriesSettingsComponent: (typeof import("./src/components/Categories/CategoriesSettingsComponent.vue"))["default"];
    CheckboxComponent: (typeof import("./src/components/ui/CheckboxComponent/CheckboxComponent.vue"))["default"];
    ChispComponent: (typeof import("./src/components/ui/ChispComponent/ChispComponent.vue"))["default"];
    ColorPickerComponent: (typeof import("./src/components/ui/ColorPickerComponent/ColorPickerComponent.vue"))["default"];
    DropdownComponent: (typeof import("./src/components/ui/DropdownComponent/DropdownComponent.vue"))["default"];
    FooterComponent: (typeof import("./src/components/Footer/FooterComponent.vue"))["default"];
    FooterInfoComponent: (typeof import("./src/components/Footer/FooterInfoComponent.vue"))["default"];
    FooterMetaComponent: (typeof import("./src/components/Footer/FooterMetaComponent.vue"))["default"];
    HeaderActionsComponent: (typeof import("./src/components/Header/HeaderActionsComponent.vue"))["default"];
    HeaderComponent: (typeof import("./src/components/Header/HeaderComponent.vue"))["default"];
    HeaderMenuComponent: (typeof import("./src/components/Header/HeaderMenuComponent.vue"))["default"];
    HomeClothesComponent: (typeof import("./src/components/Home/HomeClothesComponent.vue"))["default"];
    HomeNewGoodsComponent: (typeof import("./src/components/Home/HomeNewGoodsComponent.vue"))["default"];
    HomePopularCategoriesComponent: (typeof import("./src/components/Home/HomePopularCategoriesComponent.vue"))["default"];
    HomePreviewComponent: (typeof import("./src/components/Home/HomePreviewComponent.vue"))["default"];
    InputComponent: (typeof import("./src/components/ui/InputComponent/InputComponent.vue"))["default"];
    ProductCardCharacteristicsComponent: (typeof import("./src/components/Product/ProductCardCharacteristicsComponent.vue"))["default"];
    ProductCardComponent: (typeof import("./src/components/Product/ProductCardComponent.vue"))["default"];
    ProductCardDescriptionComponent: (typeof import("./src/components/Product/ProductCardDescriptionComponent.vue"))["default"];
    ProductCardGalleryComponent: (typeof import("./src/components/Product/ProductCardGalleryComponent.vue"))["default"];
    ProductCardInfoColors: (typeof import("./src/components/Product/ProductCardInfoColors.vue"))["default"];
    ProductCardInfoColorsComponent: (typeof import("./src/components/Product/ProductCardInfoColorsComponent.vue"))["default"];
    ProductCardInfoComponent: (typeof import("./src/components/Product/ProductCardInfoComponent.vue"))["default"];
    ProductCardInfoSizeComponent: (typeof import("./src/components/Product/ProductCardInfoSizeComponent.vue"))["default"];
    ProductCardInfoSizesComponent: (typeof import("./src/components/Product/ProductCardInfoSizesComponent.vue"))["default"];
    ProductCardInfoTotalComponent: (typeof import("./src/components/Product/ProductCardInfoTotalComponent.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    SettingCategoryComponent: (typeof import("./src/components/Settings/SettingCategoryComponent.vue"))["default"];
    SettingColorComponent: (typeof import("./src/components/Settings/SettingColorComponent.vue"))["default"];
    SettingFloorComponent: (typeof import("./src/components/Settings/SettingFloorComponent.vue"))["default"];
    SettingPriceComponent: (typeof import("./src/components/Settings/SettingPriceComponent.vue"))["default"];
    SettingSizeComponent: (typeof import("./src/components/Settings/SettingSizeComponent.vue"))["default"];
  }
}
