/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CActions: typeof import('./src/components/Header/CActions.vue')['default']
    CFooter: typeof import('./src/components/Footer/CFooter.vue')['default']
    CHeader: typeof import('./src/components/Header/CHeader.vue')['default']
    CMain: typeof import('./src/components/Main/CMain.vue')['default']
    CMenu: typeof import('./src/components/Header/CMenu.vue')['default']
    ElMessage: typeof import('element-plus/es')['ElMessage']
  }
}
